# Generated by Django 5.1.1 on 2024-10-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='reseña',
            new_name='resena',
        ),
    ]
